import { AnimeList, SearchField, ShoppingCart } from '@/components'
import { getList, searchItem } from '@/redux/animeSlice'
import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import s from '../styles/Home.module.css'

export default function Home() {
  const dispatch = useDispatch()

  useEffect(() => {
    dispatch(getList(1))
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className={s.header}>
          <SearchField />
          <ShoppingCart />
        </div>

        <AnimeList />
      </main>
    </>
  )
}
